# Generated by Django 6.0 on 2026-01-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(help_text='Positif pour entrée, négatif pour sortie', verbose_name='Quantité')),
                ('previous_quantity', models.IntegerField(verbose_name='Stock précédent')),
                ('new_quantity', models.IntegerField(verbose_name='Nouveau stock')),
                ('reason', models.CharField(blank=True, help_text='Ex: Livraison commande, Arrivage fournisseur, Vente directe', max_length=255, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order', verbose_name='Commande liée')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
