# Generated by Django 6.0 on 2026-01-02 18:49

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('local_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID local (sync)')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('delivery_address', models.TextField(verbose_name='Adresse de livraison')),
                ('delivery_date', models.DateField(verbose_name='Date de livraison')),
                ('delivery_status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_preparation', 'En préparation'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20, verbose_name='Statut livraison')),
                ('payment_status', models.CharField(choices=[('non_payee', 'Non payée'), ('payee', 'Payée')], default='non_payee', max_length=20, verbose_name='Statut paiement')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('total_price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Prix total (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'orders',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Sous-total (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'order_items',
            },
        ),
    ]
