# Generated by Django 6.0 on 2026-01-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default='', verbose_name='Adresse de livraison'),
        ),
    ]
