# Generated by Django 6.0 on 2026-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
    ]
