# Generated by Django 6.0 on 2026-01-08 17:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro de reçu')),
                ('local_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID local')),
                ('client_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du client')),
                ('client_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('payment_method', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte Bancaire'), ('credit', 'Crédit')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('payment_status', models.CharField(choices=[('payee', 'Payée'), ('en_attente', 'En attente'), ('partielle', 'Paiement partiel')], default='payee', max_length=20, verbose_name='Statut de paiement')),
                ('subtotal', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Sous-total')),
                ('discount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Remise')),
                ('total_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant total')),
                ('amount_paid', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant payé')),
                ('amount_due', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Reste à payer')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix unitaire')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Sous-total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Produit')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Article de vente',
                'verbose_name_plural': 'Articles de vente',
                'db_table': 'sale_items',
            },
        ),
    ]
